services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  lamp-server:
    image: php:8.2-apache
    container_name: lamp-server
    ports:
      - "8080:80"
    volumes:
      - ./service.php:/var/www/html/service.php
    environment:
      - 'CDEK_LOGIN=${CDEK_LOGIN}'
      - 'CDEK_PASSWORD=${CDEK_PASSWORD}'
    restart: always

  honey-shop-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: honey-shop-app
    ports:
      - '8443:8443'
    environment:
        - 'DB_DATASOURCE=${DB_DATASOURCE}'
        - 'DB_USERNAME=${DB_USERNAME}'
        - 'DB_PASSWORD=${DB_PASSWORD}'
        - 'REDIS_HOST=redis'
        - 'REDIS_PORT=6379'
        - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
        - 'MYAPP_SECRET_KEY=${MYAPP_SECRET_KEY}'
        - 'MYAPP_SHOP_ID=${MYAPP_SHOP_ID}'
        - 'MYAPP_SHOP_YOOKASSA_API_KEY=${MYAPP_SHOP_YOOKASSA_API_KEY}'
        - 'KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}'
        - 'MAIL_USERNAME=${MAIL_USERNAME}'
        - 'MAIL_PASSWORD=${MAIL_PASSWORD}'
    volumes:
      - ./uploads:/app/uploads/img
    depends_on:
      - postgres
      - redis
