global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    scheme: https
    tls_config:
        insecure_skip_verify: true
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['honey-shop-app:8443']

